### ISSUE TITLE
OP_CODESEPARATOR

### ISSUE THREAD

**Issue by monsterbitar** [bitjson/bch-vm-limits#1]
Does the OP_CODESEPARATOR have any impact on these limitations?

**Comment by bitjson** [comment]
I don't expect there to be any interaction with `OP_CODESEPARATOR`. Is there some scenario you have in mind specifically?

**Comment by monsterbitar** [comment]
> I don't expect there to be any interaction with `OP_CODESEPARATOR`. Is there some scenario you have in mind specifically?

No, it's just an odd opcode that we have been considering to use at GP in order to work with existing limitations when doing introspection.
