### ISSUE TITLE
Should we limit the depth of the evaluation stack?

### ISSUE THREAD

**Issue by bitjson** [bitjson/bch-vm-limits#11]
As mentioned in the CHIP, an [O(1) Execution Stack](https://github.com/bitcoin/bitcoin/pull/16902) isn't very hard to implement. But maybe a worthwhile research question before we essentially require implementations to think about this: is practically-unlimited "evaluation stack depth" desirable?

Would the protocol actually be made simpler by adding fixed depth limit on `OP_IF` and `OP_NOTIF`?

Or maybe evaluation stack manipulation is still so much faster than hash digest iterations that we don't need to care about this problem either way?

I'd love to hear about the worst-case performance of naively-implemented evaluation stacks in various languages and VM implementations.

**Comment by cculianu** [comment]
Leaving note here: FWIW BCHN uses O(1) conditional stack.

**Comment by bitjson** [comment]
Resolved and rationale documented in [Rationale: Retention of Control Stack Limit](https://github.com/bitjson/bch-vm-limits/blob/b476674575e0f5d2ccdf60d5091a3b882b38b00c/rationale.md#retention-of-control-stack-limit) 🚀
