### ISSUE TITLE
How are hashing ops limits applied in the case of p2sh?

### ISSUE THREAD

**Issue by cculianu** [bitjson/bch-vm-limits#14]
In the spec, what is the definition of an “evaluation” for the purposes of hitting the hash ops limit? For example, a p2sh:

(1) evaluates the locking script, hashing the redeemscript via e.g. OP_HASH160 or whatever.
(2) then it evaluates the redeemscript (which itself may contain further hashing op codes).

When (2) begins evaluating redeemscript, is the hash count reset to 0 or does it continue where (1) left off for the counts?

EDIT: So far in my test implementation, I am having it *not* reset to 0 as it proceeds to the redeemscript, thus the hashOps count is 1 when the redeemScript begins execution in the p2sh case.

**Comment by bitjson** [comment]
Fixed and noted in changelog (`Note accounting of P2SH redeem bytecode digest iterations (#14)`) by https://github.com/bitjson/bch-vm-limits/commit/4eba48ea4648a5ad39f40ff11bfebbe3459fca83 🚀
