### ISSUE TITLE
Attack in a single TX vs over multiple TXs?

### ISSUE THREAD

**Issue by monsterbitar** [bitjson/bch-vm-limits#2]
Some concerns about lifting the limits are about reducing the maximum damage that a single transactions can do, but looking at the examples I get a feeling that with a small setup and teardown costs, you can still do these attacks today by simply doing multiple transactions.

Would that mean that the practical attacks are limited to things that scale non-linearly within a transaction?

**Comment by bitjson** [comment]
> Would that mean that the practical attacks are limited to things that scale non-linearly within a transaction?

Yes, exactly – the only meaningful attacks are constructions that can become more expensive as a transaction gets larger. In practice, that's basically only hashing. (`OP_IF` and `OP_ROLL` can also be expensive when naively implemented, but when implemented properly, they're millions of times less expensive than hashing.)

So if we limit hashing and stack memory usage, (I believe) all "attacks" become quantifiable in terms of CPU/memory usage per byte (and therefore constrained by transaction fees). And in practice, these attacks are so insignificant they are indistinguishable from just spamming blocks. (If you're running a validating node, you probably wouldn't notice a CPU/memory usage difference between an "attack" full of hashing-limited transactions and an "attack" full of `OP_RETURN` data.) 

Be sure to check out the [Calculations section here](https://github.com/bitjson/bch-vm-limits#exclusion-of-additional-relay-policy-limits) too.
