### ISSUE TITLE
Protection against unknown vectors

### ISSUE THREAD

**Issue by monsterbitar** [bitjson/bch-vm-limits#3]
One thing that's a concern is that the currently best known attack scripts might not be the actually best attack scripts, and the current limitation might function as protection against unknown vectors as a side-effect of being so restricting.

If I understand correctly, the reason for such a large jump (20x element size, opcode limited only by other limitations) is to remain backwards compatible with potentially existing UTXOs.

While discussing this the argument that fees protect against the unknown attacks if we limit the extraordinarily high-cost operation - is that a valid reasoning? (ie, if all unrestricted opcodes have the same true cost, then to abuse them by using more of them, the fees will be regulating the potential worst case issue to a monetary function?)

**Comment by bitjson** [comment]
> the currently best known attack scripts might not be the actually best attack scripts

It's definitely possible that I'm overlooking some way to further optimize the [attack/benchmark contracts](https://github.com/bitjson/bch-vm-limits#benchmarks) – I'd love to get as many eyes on those as possible! (If so, we should raise these new `660 digest iteration` and `130,000 byte` limits proportionately.)

However, I'm quite confident that we've reviewed the VM enough in the past 10 years to have noticed any other sources of worse-than-linear time performance. (E.g. the `OP_ROLL` and `OP_IF` benchmarks test [issues that have been well-known](https://bitslog.com/2017/04/17/new-quadratic-delays-in-bitcoin-scripts/) now for at least 4 years.) Other than hashing and signature verification, it's easy to confirm that all other operations are possible in constant time (if `OP_ROLL` and `OP_IF` are properly implemented). 

It's definitely important that we be cautious about changes like this, but to put things in perspective, in order for a yet-unknown vector to require equivalent resources as a hashing-limited transaction, it would need to be many millions of times less theoretically-efficient than `OP_ADD`. For example, even if you implement `OP_ROLL` by copying the entire stack, you're still many orders of magnitude away from the worst-case hashing performance in worst-case nodes (running on a software-virtualized host).

A [related comment from the BCH compilers discussion](https://t.me/bch_compilers/4800):

> In short: if we picked anything below 130,000, we risk invalidating certain types of transactions which are already theoretically possible. Since these are already possible (and really inexpensive to validate anyways), I don't think there's a strong arguement to make for reducing that limit. And I didn't want to advocate for raising any limits in this spec because I don't think they need to be raised. Easier to change one thing at a time – this proposal keeps the effective limits on CPU and memory usage the same. It's just that the way we measured them before made them only really useful to attackers – honest contracts can't do much with a 201 operation limit, but attackers could still make transactions which are **many millions of times more expensive to validate** than a 201 operation contract with only math and stack operations. TL;DR: the current way the VM limits CPU and memory use is naive and destructive.

All that said, it might be valuable to address the sigchecks limit somewhere in this CHIP, if only for informational purposes. 🤔 That's the only other part of the VM which can consume a lot of resources, so it might be valuable for readers to have that context.

**Comment by bitjson** [comment]
The latest version (https://github.com/bitjson/bch-vm-limits/commit/e686b981e14f9f69433682dda9df8b204c66b709) now explicitly mentions that SigChecks are not modified, so I think that covers the actionable items in this issue. (That may change with https://github.com/bitjson/bch-vm-limits/issues/9, but further discussion can happen in that issue.)

We'll certainly need to continue hammering on the proposed limits to ensure they're sufficient, but I think any discovered problems should now generate new GitHub issues.

Closing for now, please let me know if I should re-open.
