### ISSUE TITLE
Recommendation from GP to help this CHIP reach minimum viability

### ISSUE THREAD

**Issue by emergent-reasons** [bitjson/bch-vm-limits#30]
This CHIP is in good condition and has undergone a long period of revisions to make it better and better.

There are a few critical things missing that would allow it to pass GP's minimum bar before considering it as a candidate for 2025 activation:

1. Explicit and careful consideration of costs is one of *the* key factors that makes CHIP process work. It is an important part of the steel man mechanism that ensures not only up sides but also down sides are considered. This CHIP must have a well considered costs section. In our estimation, it can probably be straightforward and simple, perhaps taking inspiration from the proposal that exists for the Big Ints CHIP.

2. Recording of social feedback and consensus building must make progress and be documented at urgent speed. Those statements cannot all be last minute as the build up of support requires time and observation of other stakeholders.

As a more minor issue, we recommend making an explicit note that  while mining fees is a topic for discussion, this CHIP is not related to fees and is not a gas system. It is very easy for a reader to look at it and think that this is a proposal to create a gas system for BCH.

In a similar line of considerations, we have posted a more specific [PR to the Big Ints CHIP](https://github.com/bitjson/bch-bigint/pull/6).

**Comment by bitjson** [comment]
Thank you again for all the feedback (here and elsewhere) @emergent-reasons, @imaginaryusername, and General Protocols! Latest PR now specifically breaks out dedicated sections for Evaluated Alternatives listing everything and linking to relevant rationale, and a Risk Assessment which expands more and links to other relevant sections. 

Thanks for recommending we mention "gas" systems, now merged here: https://github.com/bitjson/bch-vm-limits/blob/master/rationale.md#exclusion-of-gas-system-behaviors

Other than final stakeholder statements (which I'll start pulling in this week), is this issue resolved and/or does GP have any additional action items for this CHIP? Thanks!

**Comment by bitjson** [comment]
Thank you again to GP for all the feedback and review, both here and on the BigInt CHIP! I'm going to close this for now, but please open new issues if you have other ideas for improvement. Thanks!

**Comment by emergent-reasons** [comment]
Thank you! We'll review once all settled.
